---
- name: Deleting SSH Key and Clean up Azure instance
  hosts: group_<groupname>
  remote_user: normaluser
  become: yes
  gather_facts: false
  tasks:
   - include_vars: other_vars/azure-instance.yml
   - include: tasks/manage-azure/deprovison-agent.yml