---
- name: Deploy Azure Instance from ARM Template
  hosts: localhost
  gather_facts: false
  tasks:
   - name: Create Azure Deploy
     azure_rm_deployment:
        state: present
        resource_group_name: ccsp
        location: eastus
        parameters:
          vhdurl:
            value: '<insertVHDurl>' 
          vmName:
            value: '<insertGroupName>'
          username:
            value: 'normaluser'
          password:
            value: 'RoadShow123'
        template_link: 'https://raw.githubusercontent.com/Shadow-Soft/roadshow2/master/lab5/files/launchsnapshot.json'
     register: details
   - debug: 
        var: details
